services:
  postgres1:
    container_name: postgres1
    restart: always
    env_file: .env
    image: postgres:12.21
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./db_config:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=student_database

    #   - CASSANDRA_START_RPC=false
    #   - CASSANDRA_CLUSTER_NAME=cassandraCluster
    #   - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
    #   - CASSANDRA_DC=datacenter1
    # Don't need to wait 60 seconds before starting cassandra these days
    # command: bash -c 'sleep 60;  /usr/local/bin/docker-entrypoint.sh cassandra -f'

  # nginx:
  #   ports:
  #     - '80:80'
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   restart: on-failure
  #   container_name: proxy
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
    # depends_on:
    #   - api
    #   - et-rabbitmq
    #   - keycloak

  student-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ['yarn', 'start']
    container_name: student-api
    depends_on:
      - postgres1
    volumes:
      - ./config:/usr/src/app/config
    environment:
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
    ports:
      - '3010:3010'

  # kt-configurator:
  #   image: kairostech.azurecr.io/kt-configurator:${VERSION_TAG_CONFIGURATOR}
  #   container_name: configurator
  #   restart: always
  #   environment:
  #     - REACT_APP_API_DEV=true
  #     - VIRTUAL_PATH=/configurator/
  #     - VIRTUAL_PORT=11111
  #   ports:
  #     - '11111:11111'

  # keycloak:
  #   image: quay.io/keycloak/keycloak:24.0.3
  #   container_name: keycloak
  #   environment:
  #     - KC_HOSTNAME_PORT=8080
  #     - KC_HOSTNAME_STRICT=false
  #     - KC_HOSTNAME_STRICT_HTTPS=false
  #     - KC_LOG_LEVEL=info
  #     - KC_METRICS_ENABLED=true
  #     - KC_HEALTH_ENABLED=true
  #     - KEYCLOAK_ADMIN=admin
  #     - KEYCLOAK_ADMIN_PASSWORD=admin
  #     - VIRTUAL_PATH=/keycloak/
  #     - VIRTUAL_PORT=8080
  #     - KC_PROXY_HEADERS=xforwarded
  #     - KC_HOSTNAME_URL=http://localhost/keycloak/
  #     - KC_HOSTNAME_ADMIN_URL=http://localhost/keycloak/
  #   volumes:
  #     - ./keycloak_data:/opt/keycloak/data
  #   command: start-dev --import-realm
  #   ports:
  #     - 8080:8080
  #   expose:
  #     - '8080'